---
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper@sha256:2d71f9e0cb3440d552ee31769a00eb813be87397bf535995aca0bd4eadc151fc
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka@sha256:01b42b29f3ab3f5c08734e1c9e78989812d1d15d6a170de0ccd3796b0a1ca6fd
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${LOCAL_IP}
      KAFKA_ZOOKEEPER_CONNECT: ${LOCAL_IP}:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${LOCAL_IP}:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafka-rest:
    image: confluentinc/cp-kafka-rest@sha256:609811e23456f5eaff49cbcea3e744a02f91d9db1407f3a52b79ec890615f61b
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: ${LOCAL_IP}:9092
      KAFKA_REST_ZOOKEEPER_CONNECT: ${LOCAL_IP}:2181
      KAFKA_REST_HOST_NAME: ${LOCAL_IP}
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,DELETE,OPTIONS'
    ports:
      - 8082:8082
    depends_on:
      - kafka

  topics-ui:
    image: landoop/kafka-topics-ui@sha256:706499fc37c67b4d3edce7a04579b8e0c420fec0aea30d893888b22d20bc99a8
    ports:
      - 8000:8000
    environment:
      KAFKA_REST_PROXY_URL: http://${LOCAL_IP}:8082
    depends_on:
      - kafka-rest
